<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class UrlRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'original_url' => 'required|url'
        ];

    }

    public function messages()
    {
        return [
           'original_url.required' => 'Original URL field is required.',
           'original_url.url'  => 'Original URL must be a valid URL.',
        ] ;// TODO: Change the autogenerated stub
    }
}
